# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PR-card' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PR-card
  pod 'Alamofire', '~> 5.2'
  pod 'Charts'
  pod 'Instructions', '~> 2.0.1'

  target 'PR-cardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PR-cardUITests' do
    # Pods for testing
  end

end
